export default {
  lang:'en',locale:'en_GB',label:'English',
  title:'Valencian Community Renovations | Apex Building Group',
  description:'Full renovations for apartments, houses and commercial spaces throughout the Valencian Community. Apex Building Group handles installations, finishes and cleaning.',
  skip:'Skip to content',navLabel:'Main navigation',menu:'Open menu',closeMenu:'Close menu',language:'Website language',
  nav:['Services','About us','Our process','Contact'],navCTA:'Discuss your project',
  hero:{
    location:'Valencian Community, Spain',kicker:'Full renovations across the Valencian Community',lines:['Spaces made', 'for the way', 'you live.'],
    text:'From the first idea to the finishing touches. We take care of the renovation so you can enjoy the result.',
    cta:'Discuss your renovation',secondary:'How we work',scroll:'Discover more',
    imageAlt:'Bright living room with wooden flooring, large windows and natural materials',imageNote:'An interior to inspire you',
  },
  benefits:[
    ['team','One team','Organisation and coordination of every trade'],
    ['plan','A complete renovation','From the first measurements to final installation'],
    ['sparkle','Cleaning included','A complimentary deep clean after renovation'],
  ],
  services:{
    label:'What we do',title:'Your plans.\nOur craftsmanship.',
    text:'A full renovation or individual jobs. We tailor the work to your property, your needs and your budget.',cta:'Discuss the work',
    items:[
      {icon:'apartment',title:'Apartments',text:'Comfortable spaces for everyday life. From refreshing the finishes to a full renovation with a new layout.',tags:['Full renovation','Kitchens & bathrooms','Finishes']},
      {icon:'house',title:'Houses',text:'Every floor and every detail considered. We bring installations, finishes and final fittings together in one process.',tags:['Complete renovation','Building services','Installation']},
      {icon:'business',title:'Commercial spaces',text:'Get your premises ready for business. We plan the space, carry out the renovation and prepare it for opening.',tags:['Offices','Shops','Business premises']},
    ],
  },
  about:{
    label:'Apex Building Group',title:'You imagine\nthe result.\nWe bring it to life.',
    text:'We are a team of renovation and finishing specialists. We work on apartments, houses and commercial spaces throughout the Valencian Community.',
    text2:'We organise the work, coordinate the trades and handle material purchasing and delivery. You work with one team, while each stage follows a clear sequence.',
    points:['Planning the work, budget and schedule','Coordinating trades and materials','Checking the result before handover'],
    imageAlt:'Contemporary home with a wooden staircase and natural finishes',caption:'From the first visit to a space ready to live in',
  },
  spaces:{
    label:'Attention to detail',title:'Beautiful to look at.\nThoughtful to live in.',
    text:'Light, texture and a practical layout. A good renovation comes together through details that make everyday life more comfortable.',
    note:'Inspiration photographs, not completed Apex projects. Interior images: Unsplash.',
    items:[
      {image:'kitchen',title:'Light and space',subtitle:'Layout and finishes',alt:'Open living space with large windows, a dining area and wooden details'},
      {image:'bathroom',title:'Everyday comfort',subtitle:'Bathrooms and plumbing',alt:'Bright bathroom with a freestanding bathtub and wall-mounted basin'},
      {image:'living',title:'Feel at home',subtitle:'Living spaces',alt:'Welcoming living room with plants and warm wooden tones'},
    ],
    projectsTitle:'Our projects',projectsText:'Spaces renovated by the Apex Building Group team.',
  },
  process:{
    label:'A clear process',title:'10 steps\nto your\nnew home.',
    text:'Every job in the right order. Open a stage to see exactly what it includes.',included:'What this stage includes',cta:'Start with a consultation',
    giftTitle:'The finishing touch is on us',giftText:'A complimentary deep clean after renovation. We hand over a clean space, ready for you to enjoy.',
    steps:[
      ['Consultation and assessment','We visit the property and discuss your ideas, budget and schedule.',['Site visit and inspection','Measurements and assessment of the current condition','Discussion of your wishes and budget','Initial cost estimate','Work and schedule planning']],
      ['Layout and design','We plan the space and develop a design project if you need one.',['Layout options','Placement of partitions and doors','Plumbing and electrical planning','Lighting, ventilation and air conditioning planning','Optional 3D visualisations','Selection of finishes, sanitaryware, doors and furniture']],
      ['Strip-out and preparation','We remove the old finishes and prepare the space for renovation.',['Removal of old finishes','Removal of floors, ceilings and partitions','Removal of doors and sanitaryware','Removal of redundant structures and services','Collection and removal of construction waste','Preparation for the next stages']],
      ['New layout and structures','We shape the space according to the agreed project.',['New walls and partitions','Plasterboard structures','Formation of door openings','Creation of niches and service enclosures','Suspended and multi-level ceilings','Acoustic and thermal insulation where needed']],
      ['Building services','We install the required services before finishing begins.',['Electrical installation','Water supply and drainage','Electrical distribution board and protective devices','Internet and low-voltage systems','Ventilation preparation','Air conditioning pipework preparation']],
      ['Surface preparation','We level and prepare the surfaces for the final finishes.',['Plastering','Levelling walls and ceilings','Floor screeding and levelling','Waterproofing wet areas','Plasterboard enclosure of structures','Preparation for tiling and painting']],
      ['Final finishes','Tiles, paint and flooring give the space its finished appearance.',['Tile and porcelain tile installation','Filling and painting walls and ceilings','Laminate, SPC and other floor coverings','Grouting and sealing','Decorative finishes']],
      ['Doors, furniture and fitting','We install the elements that make your space ready to use.',['Interior doors','Door trims and skirting boards','Furniture assembly and installation','Kitchen component installation','Mirrors, curtain rails and interior accessories','Adjustment of doors, furniture and fittings']],
      ['Final electrical and plumbing','We connect the equipment and check every necessary point.',['Sockets and switches','Light fittings and decorative lighting','Appliance connections','Toilet, basin and tap installation','Shower systems and bathtubs','Final checks of electrical, water and drainage systems']],
      ['Final checks and cleaning','We check the result and hand over a space ready to move into.',['Final quality check','Building services checks','Correction of identified issues','Cleaning surfaces, floors and tiles','Removal of building dust and material residue','Complimentary deep cleaning']],
    ],
  },
  team:{
    label:'Specialists in their craft',title:'Different trades.\nOne team.',
    text:'We bring every trade into one coordinated process, from the building services to the last interior details.',
    roles:[
      ['water','Plumbing','Water supply, drainage and equipment installation.'],
      ['electric','Electrical','Wiring, distribution boards, sockets and lighting.'],
      ['finish','Finishing','Tiles, paint, flooring and installation.'],
      ['truck','Transport','Material delivery and construction waste removal.'],
    ],
  },
  faq:{
    label:'Before we begin',title:'What you\nmight want to know.',
    items:[
      ['How much does a full renovation cost?','The cost depends on the size and condition of the property, the scope of work and the materials you choose. After a site visit and a discussion of your needs, we prepare an initial estimate. Get in touch to discuss your property.'],
      ['Can I book individual jobs?','Yes. Alongside full renovations, we offer plumbing, electrical installation, finishing, installation and transport. Tell us what you need and we can discuss the right scope of work.'],
      ['Who handles the materials?','We can manage material purchasing and delivery. We discuss finishes, sanitaryware, doors and furniture with you during the planning stage.'],
      ['How long will the renovation take?','We establish the schedule after visiting the property and agreeing the work. It depends on the condition of the space, the building services, chosen materials and the sequence of stages.'],
      ['Do I need a full design project?','No. We always discuss the layout, while a full design project and 3D visualisations are prepared when needed and at your request.'],
      ['What happens at handover?','We inspect the work and building services, correct any identified issues and complete the final cleaning. The deep clean is complimentary, so we hand over a clean space ready to use.'],
    ],
  },
  contact:{
    label:'Let’s start a conversation',title:'Your space has\npotential.\nLet’s bring it out.',
    text:'Tell us about the property and your plans. We can discuss the work, budget and first visit.',
    phoneLabel:'Give us a call',emailLabel:'Email us',area:'Working throughout the Valencian Community',formTitle:'Tell us about your project',
    name:'Your name',namePlaceholder:'Your name',phone:'Phone number',phonePlaceholder:'+34 600 000 000',
    type:'Property type',types:['Choose a type','Apartment','House','Commercial property','Other'],
    message:'What would you like to do?',messageOptional:'optional',messagePlaceholder:'For example: renovation of a 70 m² apartment in Valencia…',
    consent:'I agree to share these details with Apex Building Group through WhatsApp to discuss my project.',privacy:'How your details are used',submit:'Discuss on WhatsApp',
    helper:'WhatsApp will open with a prepared message. Send it to start the conversation.',nojs:'Enable JavaScript to use the form or contact us directly:',
    opened:'Your message is ready. Send it in WhatsApp so we receive your enquiry.',continue:'Open WhatsApp',fallback:'Or email your project details',
    invalidPhone:'Enter a valid phone number with 7 to 15 digits.',waIntro:'Hello! I would like to discuss a renovation with Apex Building Group.',waName:'Name',waPhone:'Phone',waType:'Property',waMessage:'Project',
  },
  footer:{tagline:'Creating spaces for life.',rights:'All rights reserved.',privacy:'Information about your data',top:'Back to top'},
  privacy:{
    title:'How your details are used',back:'Back to the website',intro:'The form prepares your enquiry and opens WhatsApp. You send the message yourself for the company to receive your details.',
    sections:[
      ['What you share','Your name, phone number, property type and work description, if provided. Please do not include documents, payment details or other sensitive information.'],
      ['Who receives it and why','You share your information with Apex Building Group so the team can answer your enquiry and discuss your renovation. For questions about your details: apexbuildinggroup.es@gmail.com.'],
      ['What the website stores','The website does not save the form content on a server and does not use analytics or advertising cookies. The hosting provider may process technical access logs under its own policy.'],
      ['Third-party services','When you open WhatsApp, Instagram or your email service, the terms of that service apply. Please check the message before sending it.'],
      ['Enquiries about your data','To request access, correction or deletion of information shared with the company, contact the email address above.'],
    ],
  },
  notFound:{title:'Page not found',text:'The address may have changed. Return to the homepage to explore our services.',cta:'Back to home'},
};
