export default {
  lang: 'es', locale: 'es_ES', label: 'Español',
  title: 'Reformas en la Comunidad Valenciana | Apex Building Group',
  description: 'Reformas integrales de pisos, casas y locales en toda la Comunidad Valenciana. Apex Building Group coordina instalaciones, acabados y limpieza final.',
  skip: 'Ir al contenido', navLabel: 'Navegación principal', menu: 'Abrir menú', closeMenu: 'Cerrar menú', language: 'Idioma del sitio',
  nav: ['Servicios', 'Nosotros', 'Cómo trabajamos', 'Contacto'], navCTA: 'Hablemos de tu proyecto',
  hero: {
    location: 'Comunidad Valenciana, España', kicker: 'Reformas integrales en la Comunidad Valenciana',
    lines: ['Espacios para', 'vivir a', 'tu manera.'],
    text: 'Desde la primera idea hasta el último detalle. Nos ocupamos de toda la reforma para que disfrutes del resultado.',
    cta: 'Hablemos de tu reforma', secondary: 'Cómo trabajamos', scroll: 'Descubre más',
    imageAlt: 'Salón luminoso con suelo de madera, grandes ventanales y materiales naturales', imageNote: 'Un interior para inspirarte',
  },
  benefits: [
    ['team', 'Un solo equipo', 'Organización y coordinación de los trabajos'],
    ['plan', 'Reforma llave en mano', 'Desde las mediciones hasta el montaje final'],
    ['sparkle', 'Limpieza de regalo', 'Limpieza general al terminar la reforma'],
  ],
  services: {
    label: 'Nuestros servicios', title: 'Tus planes.\nNuestro trabajo.',
    text: 'Una reforma completa o trabajos puntuales. Adaptamos la propuesta a tu espacio, tus necesidades y tu presupuesto.', cta: 'Consultar trabajos',
    items: [
      { icon: 'apartment', title: 'Pisos', text: 'Creamos espacios cómodos para vivir. Desde renovar los acabados hasta una reforma integral con una nueva distribución.', tags: ['Reforma integral', 'Cocinas y baños', 'Acabados'] },
      { icon: 'house', title: 'Casas', text: 'Cuidamos cada planta y cada detalle. Coordinamos instalaciones, acabados y montaje final dentro de un mismo proceso.', tags: ['Reforma completa', 'Instalaciones', 'Montaje'] },
      { icon: 'business', title: 'Locales', text: 'Preparamos tu local para trabajar. Planificamos el espacio, ejecutamos la reforma y lo dejamos listo para abrir.', tags: ['Oficinas', 'Tiendas', 'Locales comerciales'] },
    ],
  },
  about: {
    label: 'Apex Building Group', title: 'Tú imaginas\nel resultado.\nNosotros lo creamos.',
    text: 'Somos un equipo de especialistas en reformas y acabados. Trabajamos en pisos, casas y locales comerciales en todo el territorio de la Comunidad Valenciana.',
    text2: 'Nos encargamos de organizar los trabajos, coordinar a los profesionales y gestionar la compra y entrega de materiales. Hablas con un solo equipo y cada etapa sigue un orden claro.',
    points: ['Planificación de trabajos, presupuesto y plazos', 'Coordinación de profesionales y materiales', 'Revisión del resultado antes de la entrega'],
    imageAlt: 'Espacio residencial contemporáneo con escalera de madera y acabados naturales', caption: 'Desde la primera visita hasta un espacio listo para vivir',
  },
  spaces: {
    label: 'Cuidamos los detalles', title: 'Bonito por fuera.\nBien pensado por dentro.',
    text: 'Luz, texturas y una distribución cómoda. Una buena reforma se construye con detalles que mejoran tu día a día.',
    note: 'Fotografías de inspiración, no proyectos realizados por Apex. Interiores: Unsplash.',
    items: [
      {image:'kitchen',title:'Luz y amplitud',subtitle:'Distribución y acabados',alt:'Espacio abierto con grandes ventanales, comedor y detalles de madera'},
      {image:'bathroom',title:'Comodidad cada día',subtitle:'Baños y fontanería',alt:'Baño luminoso con bañera exenta y lavabo suspendido'},
      {image:'living',title:'A gusto en casa',subtitle:'Espacios para vivir',alt:'Salón acogedor con plantas y tonos cálidos de madera'},
    ],
    projectsTitle: 'Nuestros proyectos', projectsText: 'Espacios en los que ha trabajado el equipo de Apex Building Group.',
  },
  process: {
    label: 'Un proceso claro', title: '10 pasos\nhasta tu\nnuevo hogar.',
    text: 'Todos los trabajos, en el orden adecuado. Abre cada etapa para ver qué incluye.', included: 'Qué incluye esta etapa', cta: 'Empezar con una consulta',
    giftTitle: 'El último detalle es un regalo', giftText: 'Limpieza general al finalizar la reforma. Te entregamos un espacio limpio y listo para vivir.',
    steps: [
      ['Consulta y valoración', 'Visitamos el inmueble y hablamos de tus ideas, presupuesto y plazos.', ['Visita e inspección del inmueble', 'Mediciones y valoración del estado actual', 'Conversación sobre necesidades y presupuesto', 'Estimación inicial del coste', 'Planificación de trabajos y plazos']],
      ['Distribución y diseño', 'Planificamos el espacio y, si lo necesitas, desarrollamos el proyecto de diseño.', ['Propuestas de distribución', 'Ubicación de tabiques y puertas', 'Planificación de fontanería y electricidad', 'Iluminación, ventilación y climatización', 'Visualizaciones 3D opcionales', 'Selección de materiales, sanitarios, puertas y muebles']],
      ['Demoliciones y preparación', 'Retiramos los acabados antiguos y preparamos el espacio para la reforma.', ['Retirada de acabados antiguos', 'Demolición de suelos, techos y tabiques', 'Retirada de puertas y sanitarios', 'Desmontaje de elementos e instalaciones que se sustituyen', 'Recogida y retirada de escombros', 'Preparación para las siguientes etapas']],
      ['Nueva distribución y estructuras', 'Damos forma al espacio según el proyecto acordado.', ['Construcción de paredes y tabiques', 'Montaje de estructuras de pladur', 'Formación de huecos para puertas', 'Creación de nichos y cajones', 'Falsos techos y techos a distintos niveles', 'Aislamiento acústico y térmico cuando sea necesario']],
      ['Instalaciones', 'Instalamos las redes necesarias antes de los acabados.', ['Instalación eléctrica', 'Abastecimiento de agua y saneamiento', 'Cuadro eléctrico y dispositivos de protección', 'Internet y redes de baja tensión', 'Preparación de ventilación', 'Preinstalación de climatización']],
      ['Preparación de superficies', 'Nivelamos y preparamos las bases para los materiales de acabado.', ['Trabajos de enlucido', 'Nivelación de paredes y techos', 'Recrecido y nivelación del suelo', 'Impermeabilización de zonas húmedas', 'Cerramiento de estructuras con pladur', 'Preparación para alicatado y pintura']],
      ['Acabados', 'El espacio toma su aspecto final con azulejos, pintura y pavimentos.', ['Colocación de azulejos y gres porcelánico', 'Masillado y pintura de paredes y techos', 'Colocación de laminado, SPC y otros pavimentos', 'Rejuntado y sellado', 'Acabados decorativos']],
      ['Puertas, muebles y montaje', 'Instalamos los elementos que hacen que el espacio esté listo para usar.', ['Puertas interiores', 'Tapajuntas y rodapiés', 'Montaje e instalación de muebles', 'Montaje de elementos de cocina', 'Espejos, barras de cortina y elementos de interior', 'Ajuste de puertas, muebles y herrajes']],
      ['Electricidad y fontanería final', 'Conectamos los equipos y revisamos todos los puntos necesarios.', ['Enchufes e interruptores', 'Luminarias e iluminación decorativa', 'Conexión de electrodomésticos', 'Instalación de inodoro, lavabo y grifería', 'Sistemas de ducha y bañera', 'Comprobación de electricidad, agua y saneamiento']],
      ['Revisión y limpieza', 'Comprobamos el resultado y entregamos un espacio listo para ocupar.', ['Control final de los trabajos', 'Comprobación de instalaciones', 'Corrección de los detalles detectados', 'Limpieza de superficies, suelos y azulejos', 'Retirada de polvo y restos de materiales', 'Limpieza general de regalo']],
    ],
  },
  team: {
    label: 'Especialistas en su oficio', title: 'Diferentes trabajos.\nUn mismo equipo.',
    text: 'Coordinamos todo el trabajo en un único proceso: desde las instalaciones hasta los últimos detalles del interior.',
    roles: [
      ['water','Fontanería','Agua, saneamiento e instalación de equipos.'],
      ['electric','Electricidad','Cableado, cuadro eléctrico, enchufes e iluminación.'],
      ['finish','Acabados','Azulejos, pintura, pavimentos y montaje.'],
      ['truck','Transporte','Entrega de materiales y retirada de escombros.'],
    ],
  },
  faq: {
    label: 'Antes de empezar', title: 'Lo que te\ngustaría saber.',
    items: [
      ['¿Cuánto cuesta una reforma integral?', 'El coste depende de la superficie, el estado del inmueble, el alcance de los trabajos y los materiales elegidos. Tras visitar el espacio y hablar de tus necesidades, preparamos una estimación inicial. Escríbenos para comentar tu proyecto.'],
      ['¿Puedo contratar trabajos puntuales?', 'Sí. Además de reformas integrales, realizamos trabajos de fontanería, instalaciones eléctricas, acabados, montaje y transporte. Cuéntanos qué necesitas y comentamos el alcance adecuado.'],
      ['¿Quién se encarga de los materiales?', 'Podemos gestionar la compra y entrega de materiales. Hablamos contigo sobre acabados, sanitarios, puertas y muebles durante la planificación.'],
      ['¿Cuánto tiempo dura la reforma?', 'Definimos los plazos después de visitar el inmueble y acordar los trabajos. Dependen del estado del espacio, las instalaciones, los materiales y el orden de las etapas.'],
      ['¿Es obligatorio un proyecto de diseño?', 'No. Siempre hablamos de la distribución, pero el proyecto completo de diseño y las visualizaciones 3D se realizan cuando son necesarios y si los deseas.'],
      ['¿Qué incluye la entrega final?', 'Revisamos los trabajos y las instalaciones, corregimos los detalles detectados y realizamos la limpieza final. La limpieza general es un regalo: entregamos el espacio limpio y listo para usar.'],
    ],
  },
  contact: {
    label: 'Empecemos hablando', title: 'Tu espacio tiene\npotencial.\nVamos a descubrirlo.',
    text: 'Cuéntanos cómo es el inmueble y qué tienes en mente. Hablamos de trabajos, presupuesto y la primera visita.',
    phoneLabel: 'Llámanos', emailLabel: 'Escríbenos', area: 'Trabajamos en toda la Comunidad Valenciana',
    formTitle: 'Cuéntanos tu proyecto', name: 'Cómo te llamas', namePlaceholder: 'Tu nombre', phone: 'Número de teléfono', phonePlaceholder: '+34 600 000 000',
    type: 'Tipo de inmueble', types: ['Elige una opción','Piso','Casa','Local comercial','Otro'],
    message: 'Qué te gustaría hacer', messageOptional: 'opcional', messagePlaceholder: 'Por ejemplo: reforma de un piso de 70 m² en Valencia…',
    consent: 'Acepto compartir estos datos con Apex Building Group a través de WhatsApp para hablar de mi proyecto.', privacy: 'Cómo se usan tus datos', submit: 'Hablar por WhatsApp',
    helper: 'Se abrirá WhatsApp con un mensaje preparado. Envíalo para iniciar la conversación.',
    nojs: 'Activa JavaScript para usar el formulario o contacta directamente:',
    opened: 'Tu mensaje está preparado. Envíalo en WhatsApp para que recibamos tu consulta.', continue: 'Abrir WhatsApp', fallback: 'O envía la información por email',
    invalidPhone: 'Introduce un teléfono válido de entre 7 y 15 dígitos.', waIntro: '¡Hola! Me gustaría hablar de una reforma con Apex Building Group.', waName:'Nombre',waPhone:'Teléfono',waType:'Inmueble',waMessage:'Proyecto',
  },
  footer: {tagline:'Creamos espacios para vivir.',rights:'Todos los derechos reservados.',privacy:'Información sobre tus datos',top:'Volver arriba'},
  privacy: {
    title:'Cómo se utilizan tus datos',back:'Volver al sitio',
    intro:'El formulario prepara el texto de tu consulta y abre WhatsApp. Tú envías el mensaje para que la empresa reciba tus datos.',
    sections:[
      ['Qué compartes','Tu nombre, teléfono, el tipo de inmueble y la descripción de los trabajos, si la incluyes. No añadas documentos, datos de pago ni otra información sensible.'],
      ['Con quién y para qué','Compartes la información con Apex Building Group para responder a tu consulta y hablar de la reforma. Para preguntas sobre tus datos: apexbuildinggroup.es@gmail.com.'],
      ['Qué guarda el sitio','El sitio no guarda el contenido del formulario en un servidor ni utiliza cookies de analítica o publicidad. El alojamiento puede tratar registros técnicos de acceso según su propia política.'],
      ['Servicios externos','Al abrir WhatsApp, Instagram o tu servicio de correo, se aplican las condiciones del servicio correspondiente. Revisa el contenido del mensaje antes de enviarlo.'],
      ['Consultas sobre tus datos','Para solicitar acceso, rectificación o eliminación de los datos que hayas compartido con la empresa, escribe al email indicado.'],
    ],
  },
  notFound:{title:'Página no encontrada',text:'Es posible que la dirección haya cambiado. Vuelve al inicio para conocer nuestros servicios.',cta:'Volver al inicio'},
};
